<?php
    /**
     * @var Inchoo\ProductFAQ\Block\FAQForm $block
     */
?>
<form action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" class="faq-form" id="faq-form" data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset faq-fieldset" data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <legend class="legend faq-legend">Ask Us A Question</legend>
        <div class="field faq-field-question required">
            <label for="question_field" class="label"><span><?= $block->escapeHtml(__('Question')) ?></span></label>
            <div class="control">
                <input type="text" name="question_field" id="question_field" class="input-text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="actions-toolbar faq-form-actions">
            <div class="primary actions-primary">
                <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Question')) ?></span></button>
            </div>
        </div>
    </fieldset>
</form>
